### ISSUE TITLE
метод **NewUser**

### ISSUE THREAD

**Issue by Morzaka** [QuarantineGameTeam/team3_qgame#14]
- [x] Дописати необхідні поля у модель User
- [x] Оновити файл створення таблиці **database/sql_query/user.sql**. Дописати необхідні поля
- [x] Відповідно до нових полів у структурі User оновити метод **NewUser** структури **UserRepository**

**Comment by PECHIVKO** [comment]
Чи є необхідність у оновленні методу NewUser? https://github.com/QuarantineGameTeam/team3_qgame/tree/update-userPe

**Comment by Morzaka** [comment]
Так звісно. Ти додав поля у структурі, тепер тобі необхідно ці поля описати у SQLquery(звпиті до БД), та оновити запит створення нової таблиці USERS
