### ISSUE TITLE
Rating command

### ISSUE THREAD

**Issue by Morzaka** [QuarantineGameTeam/team3_qgame#35]
Користувач коли вводить цю команду, то він має отримати такі дані, що описані в [діаграмі.](https://docs.google.com/drawings/d/1wsXLmmX7zsF-Fx9ZqFl80cYp7SAlB3ZsSUl4drGO3zk/edit)
- [ ] Створити команду <kbd>/rating</kbd>
- [ ] Додати відстуні поля у структурі і sql запитах
- [ ] Метод що реагує на цю команду має:
витягти відповідні дані(інтелект, сила, атака, інвентар) з БД про користувача і вивести відповідні нва екран.

Завдання з зіркою ---
Вивести загальний рейтинг користувача по відношенню до інших, що записанні в БД

**Comment by Milkadpua** [comment]
Начебто зрозуміло
