### ISSUE TITLE
Fight process

### ISSUE THREAD

**Issue by PECHIVKO** [QuarantineGameTeam/team3_qgame#38]
- [x] створити клавіатуру для Нападаючого
- [x] створити клавіатуру для захисту

- [x] створити обробку клавіатури нападаючого
- [x] створити обробку клавіатури захисту

- [x] створити розрахунок битв

- [x] створити вибір переможця

**Comment by PECHIVKO** [comment]
@Morzaka як гравець може отримати інформацію (callback) від ворога?

**Comment by Morzaka** [comment]
Хороше запитання. Треба ще продумати логіку так, щоб відбувалась послідовність дій. Тобто щоб хтось з гравців під час бою не зміг зробити 2 кроки підряд.
